pipeline {
    agent {
        label "moon_build_ubuntu || sun64"
    }
    environment {
        GOOGLE_CHAT_TOKEN = credentials('google-chat-token-ymkim')

        RUSTUP_HOME = "/opt/rust/rustup"
        PATH = "$PATH:/opt/rust/cargo/bin"
    }
    stages {
        stage('target: host') {
            steps {
                hangoutsNotify token: "$GOOGLE_CHAT_TOKEN",
                    message: "${env.BUILD_TIMESTAMP}\nSTART [${env.NODE_NAME}]",
                    threadByJob: true

                echo "Building..."
                sh '''
                    export
                    tree
                    cd hello_world 
                    cargo build --release
                '''
            }
        }
        stage('prepare cross compile workdir') {
            steps {
                sh """
                    echo "BUILD_ID=${env.BUILD_ID}"
                    mkdir -p /tmp/${env.BUILD_ID}
                    cp -r . /tmp/${env.BUILD_ID}
                """
            }
        }
        stage('target: x86_64-pc-windows-gnu') {
            steps {
                sh """
                    cd /tmp/${env.BUILD_ID}
                    export
                    tree
                    cd hello_world
                    pwd
                    ls -al
                    cross build --release --target x86_64-pc-windows-gnu
                """
            }
        }
        stage('Archive') {
            when {
                expression { currentBuild.resultIsBetterOrEqualTo('SUCCESS') }
            }
            steps {
                echo "Archiving artifacts..."
                //archiveArtifacts artifacts: '**/release/hello_world', fingerprint: true
            }
        }
    }
    post {
        always {
            echo "Google Chat Notification: ${currentBuild.currentResult}"
            hangoutsNotify token: "$GOOGLE_CHAT_TOKEN",
                message: "END [${currentBuild.currentResult}]",
                threadByJob: true
        }
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: "5", artifactNumToKeepStr: "5" ))
    }
}
